# Generated by Django 4.2.2 on 2023-06-16 12:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SpecialCare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sip", models.BooleanField(default=False, verbose_name="SIP")),
                (
                    "pob",
                    models.CharField(max_length=255, verbose_name="place of birth"),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "id_band",
                    models.BooleanField(default=False, verbose_name="any ID band"),
                ),
                (
                    "neo_record_no",
                    models.CharField(
                        max_length=255, null=True, verbose_name="neonatal record number"
                    ),
                ),
                (
                    "mat_record_no",
                    models.CharField(
                        max_length=255, null=True, verbose_name="maternal record number"
                    ),
                ),
                (
                    "mother_name",
                    models.CharField(max_length=255, verbose_name="mother's name"),
                ),
                (
                    "stays_same_place",
                    models.BooleanField(
                        default=False, verbose_name="same place as patient"
                    ),
                ),
                (
                    "stays_other_place",
                    models.BooleanField(default=False, verbose_name="other place"),
                ),
                ("stays_home", models.BooleanField(default=False, verbose_name="home")),
                ("dead", models.BooleanField(default=False)),
                (
                    "health_normal",
                    models.BooleanField(default=False, verbose_name="normal"),
                ),
                (
                    "health_critical",
                    models.BooleanField(default=False, verbose_name="critical"),
                ),
                (
                    "idd_new_born",
                    models.BooleanField(
                        default=False, verbose_name="identified her newborn"
                    ),
                ),
                (
                    "father_name",
                    models.CharField(
                        max_length=255, null=True, verbose_name="father's name"
                    ),
                ),
                (
                    "father_addr",
                    models.CharField(
                        max_length=255, null=True, verbose_name="father's address"
                    ),
                ),
                (
                    "father_email",
                    models.EmailField(
                        max_length=254, null=True, verbose_name="father's email"
                    ),
                ),
                (
                    "father_phone",
                    models.CharField(
                        max_length=255, null=True, verbose_name="father's phones"
                    ),
                ),
                (
                    "trans_same_place",
                    models.BooleanField(default=False, verbose_name="delivery room"),
                ),
                (
                    "trans_other_place",
                    models.BooleanField(default=False, verbose_name="other place"),
                ),
                (
                    "trans_readmission",
                    models.BooleanField(default=False, verbose_name="readmission"),
                ),
                (
                    "trans_reason",
                    models.CharField(
                        max_length=255, null=True, verbose_name="reason for admission"
                    ),
                ),
                ("trans_air", models.BooleanField(default=False, verbose_name="air")),
                ("trans_land", models.BooleanField(default=False, verbose_name="land")),
                (
                    "trans_km",
                    models.CharField(
                        max_length=4, null=True, verbose_name="distance (km)"
                    ),
                ),
                (
                    "trans_dura",
                    models.CharField(
                        max_length=4, null=True, verbose_name="duration (hrs)"
                    ),
                ),
                (
                    "incubator",
                    models.BooleanField(default=False, verbose_name="incubator"),
                ),
                ("iv", models.BooleanField(default=False, verbose_name="I/V")),
                (
                    "monitors",
                    models.BooleanField(default=False, verbose_name="monitors"),
                ),
                ("oxygen", models.BooleanField(default=False, verbose_name="oxygen")),
                ("cpap", models.BooleanField(default=False, verbose_name="CPAP")),
                ("ettube", models.BooleanField(default=False, verbose_name="ETTube")),
                (
                    "is_drugged",
                    models.BooleanField(default=False, verbose_name="drugs"),
                ),
                (
                    "drugs",
                    models.CharField(max_length=255, null=True, verbose_name="drugs"),
                ),
                ("iv_vol", models.CharField(max_length=3, null=True)),
                ("iv_type", models.CharField(max_length=255, null=True)),
                (
                    "trans_comp",
                    models.BooleanField(
                        default=False, verbose_name="complication during transport"
                    ),
                ),
                (
                    "admin_to",
                    models.CharField(
                        max_length=255, null=True, verbose_name="admitted to"
                    ),
                ),
                ("nurse", models.CharField(max_length=255, null=True)),
                ("doctor", models.CharField(max_length=255, null=True)),
                (
                    "admin_date_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="date of admission",
                    ),
                ),
                (
                    "admin_age",
                    models.CharField(
                        max_length=255, null=True, verbose_name="age of patient"
                    ),
                ),
            ],
        ),
    ]
