# Generated by Django 4.2.2 on 2023-06-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specialcare",
            name="doctor",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="specialcare",
            name="drugs",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="drugs"
            ),
        ),
        migrations.AlterField(
            model_name="specialcare",
            name="father_addr",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="father's address"
            ),
        ),
        migrations.AlterField(
            model_name="specialcare",
            name="father_email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="father's email"
            ),
        ),
        migrations.AlterField(
            model_name="specialcare",
            name="father_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="father's name"
            ),
        ),
        migrations.AlterField(
            model_name="specialcare",
            name="iv_type",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="I/V Type"
            ),
        ),
        migrations.AlterField(
            model_name="specialcare",
            name="iv_vol",
            field=models.CharField(
                blank=True, max_length=3, null=True, verbose_name="I/V Volume"
            ),
        ),
        migrations.AlterField(
            model_name="specialcare",
            name="nurse",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="specialcare",
            name="trans_dura",
            field=models.CharField(
                blank=True, max_length=4, null=True, verbose_name="duration (hrs)"
            ),
        ),
        migrations.AlterField(
            model_name="specialcare",
            name="trans_km",
            field=models.CharField(
                blank=True, max_length=4, null=True, verbose_name="distance (km)"
            ),
        ),
    ]
