# Generated by Django 4.2.2 on 2023-06-16 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_specialcare_doctor_alter_specialcare_drugs_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.RemoveField(
            model_name="specialcare",
            name="trans_air",
        ),
        migrations.AlterField(
            model_name="specialcare",
            name="id_band",
            field=models.BooleanField(default=False, verbose_name="ID band"),
        ),
        migrations.AlterField(
            model_name="specialcare",
            name="stays_same_place",
            field=models.BooleanField(default=False, verbose_name="same place"),
        ),
        migrations.AlterField(
            model_name="specialcare",
            name="trans_readmission",
            field=models.BooleanField(default=False, verbose_name="re-admission"),
        ),
        migrations.AlterField(
            model_name="specialcare",
            name="trans_reason",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="reason for admission",
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="transport",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.transport",
            ),
        ),
    ]
