# Generated by Django 4.2.2 on 2023-06-16 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_remove_specialcare_trans_land_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specialcare",
            name="transport",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.transport",
            ),
        ),
    ]
