# Generated by Django 4.2.2 on 2023-06-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_specialcare_sip"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="specialcare",
            name="dead",
        ),
        migrations.RemoveField(
            model_name="specialcare",
            name="health_critical",
        ),
        migrations.RemoveField(
            model_name="specialcare",
            name="health_normal",
        ),
        migrations.RemoveField(
            model_name="specialcare",
            name="stays_home",
        ),
        migrations.RemoveField(
            model_name="specialcare",
            name="stays_other_place",
        ),
        migrations.RemoveField(
            model_name="specialcare",
            name="stays_same_place",
        ),
        migrations.RemoveField(
            model_name="specialcare",
            name="trans_other_place",
        ),
        migrations.RemoveField(
            model_name="specialcare",
            name="trans_readmission",
        ),
        migrations.RemoveField(
            model_name="specialcare",
            name="trans_same_place",
        ),
        migrations.RemoveField(
            model_name="specialcare",
            name="transport",
        ),
        migrations.AddField(
            model_name="specialcare",
            name="health_status",
            field=models.CharField(
                choices=[("N", "Normal"), ("C", "Critical")],
                default="N",
                max_length=1,
                verbose_name="Health status",
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="stays_at",
            field=models.CharField(
                choices=[
                    ("S", "Same place"),
                    ("O", "Other place"),
                    ("H", "Home"),
                    ("H", "Dead"),
                ],
                default="S",
                max_length=1,
                verbose_name="Stays at",
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="trans_from",
            field=models.CharField(
                choices=[
                    ("S", "Same place (delivery room)"),
                    ("O", "Other place"),
                    ("RA", "Re-admission"),
                ],
                default="S",
                max_length=2,
                verbose_name="Transport from",
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="transport_type",
            field=models.CharField(
                choices=[("A", "Air"), ("L", "Land")],
                default="L",
                max_length=1,
                verbose_name="Transport Type",
            ),
        ),
        migrations.AlterField(
            model_name="specialcare",
            name="id_band",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="Y",
                max_length=1,
                verbose_name="ID band",
            ),
        ),
        migrations.AlterField(
            model_name="specialcare",
            name="idd_new_born",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="Y",
                max_length=1,
                verbose_name="Identified her newborn",
            ),
        ),
    ]
