# Generated by Django 4.2.2 on 2023-06-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_remove_specialcare_dead_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Transport",
        ),
        migrations.AddField(
            model_name="specialcare",
            name="address",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="age",
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="alert",
            field=models.CharField(
                choices=[("N", "Normal"), ("C", "Coma")],
                default="N",
                max_length=1,
                verbose_name="alertness",
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="anc",
            field=models.CharField(max_length=50, null=True, verbose_name="ANC"),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="apgars",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="apneas",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                help_text="treated",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="ax_temp",
            field=models.CharField(
                max_length=255, null=True, verbose_name="axillary temperature"
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="birth_asp",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                max_length=1,
                verbose_name="birth asphyxia",
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="bpd",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                max_length=1,
                verbose_name="BPD",
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="bwt",
            field=models.CharField(max_length=50, null=True, verbose_name="BWT"),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="cyano",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                max_length=1,
                verbose_name="cyanosis",
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="delivery_type",
            field=models.CharField(
                max_length=50, null=True, verbose_name="type of delivery"
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="diseases",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")], default="N", max_length=1
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="diur",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                max_length=1,
                verbose_name="diuresis",
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="dob",
            field=models.DateField(null=True, verbose_name="date of birth"),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="edd",
            field=models.CharField(max_length=50, null=True, verbose_name="EDD"),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="fio",
            field=models.CharField(max_length=255, null=True, verbose_name="fio2"),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="first_report",
            field=models.CharField(
                choices=[("D", "Direct"), ("P", "Phone"), ("ND", "Not done")],
                max_length=2,
                null=True,
                verbose_name="1st report to family",
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="ga",
            field=models.CharField(max_length=50, null=True, verbose_name="GA"),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="gender",
            field=models.CharField(
                choices=[
                    ("U", "Unspecified"),
                    ("M", "Male"),
                    ("F", "Female"),
                    ("O", "Other"),
                ],
                default="U",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="gest_age",
            field=models.CharField(
                help_text="Weeks/Days",
                max_length=255,
                null=True,
                verbose_name="gestational age",
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="gp_rh",
            field=models.CharField(max_length=50, null=True, verbose_name="Gp/Rh"),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="hb_elec",
            field=models.CharField(max_length=50, null=True, verbose_name="Hb elec"),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="hc",
            field=models.CharField(max_length=50, null=True, verbose_name="HC"),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="head_c",
            field=models.CharField(
                help_text="cm",
                max_length=3,
                null=True,
                verbose_name="head circumference",
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="hep_b",
            field=models.CharField(max_length=50, null=True, verbose_name="Hep B"),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="hiv",
            field=models.CharField(max_length=50, null=True, verbose_name="HIV"),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="hmd",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                max_length=1,
                verbose_name="HMD",
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="length",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="lmp",
            field=models.CharField(max_length=50, null=True, verbose_name="LMP"),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="nec",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                max_length=1,
                verbose_name="NEC",
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="pale",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")], default="N", max_length=1
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="parity",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="pda",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                help_text="treated",
                max_length=1,
                verbose_name="PDA",
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="per_hiv",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                max_length=1,
                verbose_name="perinatal HIV",
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="pneum",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                max_length=1,
                verbose_name="pneumothorax",
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="pphn",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                max_length=1,
                verbose_name="PPHN",
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="rds",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                max_length=1,
                verbose_name="RDS",
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="rds_meconium",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                max_length=1,
                verbose_name="RDS w/meconium",
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="rub",
            field=models.CharField(max_length=50, null=True, verbose_name="Rubella"),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="sa02",
            field=models.CharField(
                max_length=255, null=True, verbose_name="sack coated oxygen"
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="sbp",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                max_length=1,
                verbose_name="Single bowel perforation",
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="seizures",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")], default="N", max_length=1
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="syp",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                max_length=1,
                verbose_name="syphilis",
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="tob",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="vdrl",
            field=models.CharField(max_length=50, null=True, verbose_name="VDRL"),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="weight",
            field=models.CharField(help_text="g", max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name="specialcare",
            name="admin_age",
            field=models.CharField(
                help_text="DD/HH",
                max_length=255,
                null=True,
                verbose_name="age of patient",
            ),
        ),
        migrations.AlterField(
            model_name="specialcare",
            name="cpap",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                max_length=1,
                verbose_name="CPAP",
            ),
        ),
        migrations.AlterField(
            model_name="specialcare",
            name="drugs",
            field=models.TextField(blank=True, null=True, verbose_name="drugs"),
        ),
        migrations.AlterField(
            model_name="specialcare",
            name="ettube",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                max_length=1,
                verbose_name="ETTube",
            ),
        ),
        migrations.AlterField(
            model_name="specialcare",
            name="father_phone",
            field=models.TextField(
                blank=True, null=True, verbose_name="father's phones"
            ),
        ),
        migrations.AlterField(
            model_name="specialcare",
            name="incubator",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                max_length=1,
                verbose_name="Incubator",
            ),
        ),
        migrations.AlterField(
            model_name="specialcare",
            name="is_drugged",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                max_length=1,
                verbose_name="Drugs",
            ),
        ),
        migrations.AlterField(
            model_name="specialcare",
            name="iv",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                max_length=1,
                verbose_name="I/V",
            ),
        ),
        migrations.AlterField(
            model_name="specialcare",
            name="monitors",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                max_length=1,
                verbose_name="Monitors",
            ),
        ),
        migrations.AlterField(
            model_name="specialcare",
            name="oxygen",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                max_length=1,
                verbose_name="Oxygen",
            ),
        ),
        migrations.AlterField(
            model_name="specialcare",
            name="stays_at",
            field=models.CharField(
                choices=[
                    ("S", "Same place"),
                    ("O", "Other place"),
                    ("H", "Home"),
                    ("D", "Dead"),
                ],
                default="S",
                max_length=1,
                verbose_name="Stays at",
            ),
        ),
        migrations.AlterField(
            model_name="specialcare",
            name="trans_comp",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                max_length=1,
                verbose_name="complication during transport",
            ),
        ),
        migrations.AlterField(
            model_name="specialcare",
            name="trans_dura",
            field=models.CharField(
                blank=True,
                help_text="HH/MM | (02/45) | 2 hrs 45 mins",
                max_length=4,
                null=True,
                verbose_name="duration",
            ),
        ),
        migrations.AlterField(
            model_name="specialcare",
            name="trans_km",
            field=models.CharField(
                blank=True,
                help_text="KM",
                max_length=4,
                null=True,
                verbose_name="distance",
            ),
        ),
    ]
