# Generated by Django 4.2.2 on 2023-06-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_delete_transport_specialcare_address_specialcare_age_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="specialcare",
            name="fio",
        ),
        migrations.AddField(
            model_name="specialcare",
            name="fio2",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Fraction of inspired oxygen"
            ),
        ),
        migrations.AlterField(
            model_name="specialcare",
            name="sa02",
            field=models.CharField(
                max_length=255, null=True, verbose_name="oxygen saturation"
            ),
        ),
    ]
