# Generated by Django 4.2.2 on 2023-06-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_specialcare_length1_alter_specialcare_gest_age_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specialcare",
            name="first_report",
            field=models.CharField(
                choices=[("D", "Direct"), ("P", "Phone"), ("ND", "Not done")],
                default="D",
                max_length=2,
                null=True,
                verbose_name="1st report to family",
            ),
        ),
        migrations.AlterField(
            model_name="specialcare",
            name="tob",
            field=models.TimeField(null=True, verbose_name="Time of birth"),
        ),
    ]
