# Generated by Django 4.2.2 on 2023-06-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_alter_specialcare_first_report_alter_specialcare_tob"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialcare",
            name="first_exam_corrected_ga",
            field=models.CharField(
                help_text="WW/DD",
                max_length=3,
                null=True,
                verbose_name="1st exam corrected GA",
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="ind_opht",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No"), ("N/A", "N/A")],
                default="N",
                max_length=3,
                verbose_name="indirect ophthalmoscopy",
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="max_grade",
            field=models.CharField(
                blank=True, help_text="(0-5)", max_length=1, null=True
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="sepsis1_agent",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="agent"
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="sepsis1_date_treated",
            field=models.DateField(null=True, verbose_name="date treated"),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="sepsis1_no_agent",
            field=models.BooleanField(default=False, verbose_name="no agent found"),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="sepsis1_yes_no",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                max_length=1,
                verbose_name="SEPSIS1",
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="sepsis2_agent",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="agent"
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="sepsis2_date_treated",
            field=models.DateField(null=True, verbose_name="date treated"),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="sepsis2_no_agent",
            field=models.BooleanField(default=False, verbose_name="no agent found"),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="sepsis2_yes_no",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                max_length=2,
                verbose_name="SEPSIS2",
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="sepsis3_agent",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="agent"
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="sepsis3_date_treated",
            field=models.DateField(null=True, verbose_name="date treated"),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="sepsis3_no_agent",
            field=models.BooleanField(default=False, verbose_name="no agent found"),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="sepsis3_yes_no",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                max_length=2,
                verbose_name="SEPSIS3",
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="sepsis4_agent",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="agent"
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="sepsis4_date_treated",
            field=models.DateField(null=True, verbose_name="date treated"),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="sepsis4_no_agent",
            field=models.BooleanField(default=False, verbose_name="no agent found"),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="sepsis4_yes_no",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                max_length=2,
                verbose_name="SEPSIS4",
            ),
        ),
        migrations.AlterField(
            model_name="specialcare",
            name="apneas",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                help_text="Treated?",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="specialcare",
            name="pda",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                help_text="Treated?",
                max_length=1,
                verbose_name="PDA",
            ),
        ),
    ]
