# Generated by Django 4.2.2 on 2023-06-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_specialcare_first_exam_corrected_ga_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialcare",
            name="surg_ind",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                max_length=2,
                verbose_name="SEPSIS4",
            ),
        ),
        migrations.AlterField(
            model_name="specialcare",
            name="max_grade",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0", "0"),
                    ("1", "1"),
                    ("2", "2"),
                    ("3", "3"),
                    ("4", "4"),
                    ("5", "5"),
                ],
                default="1",
                max_length=1,
                null=True,
            ),
        ),
    ]
