# Generated by Django 4.2.2 on 2023-06-19 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_alter_specialcare_max_grade_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="specialcare",
            name="max_grade",
        ),
        migrations.AddField(
            model_name="specialcare",
            name="birth_asph_seiz",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                max_length=2,
                verbose_name="birth asphyxia with seizures",
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="brain_max_grade",
            field=models.CharField(
                choices=[("1", "1"), ("2", "2"), ("3", "3"), ("4", "4"), ("5", "5")],
                default="1",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="intra_hemo",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                max_length=2,
                verbose_name="intracranial hemorrhage",
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="leukom",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                max_length=2,
                verbose_name="leukomalacia",
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="rop_max_grade",
            field=models.CharField(
                choices=[
                    ("0", "0"),
                    ("1", "1"),
                    ("2", "2"),
                    ("3", "3"),
                    ("4", "4"),
                    ("5", "5"),
                ],
                default="0",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="us_scan",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                max_length=2,
                verbose_name="US scan",
            ),
        ),
    ]
