# Generated by Django 4.2.2 on 2023-06-19 21:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_remove_specialcare_max_grade_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="specialcare",
            old_name="sepsis4_agent",
            new_name="sepsis_agent",
        ),
        migrations.RenameField(
            model_name="specialcare",
            old_name="sepsis4_date_treated",
            new_name="sepsis_date_treated",
        ),
        migrations.RenameField(
            model_name="specialcare",
            old_name="sepsis4_no_agent",
            new_name="sepsis_no_agent",
        ),
        migrations.RemoveField(
            model_name="specialcare",
            name="sepsis4_yes_no",
        ),
        migrations.AddField(
            model_name="specialcare",
            name="indo_treat",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                max_length=2,
                verbose_name="indo/ibuprof",
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="other",
            field=models.CharField(
                blank=True, max_length=25, null=True, verbose_name="Code and name"
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="other1",
            field=models.CharField(
                blank=True, max_length=25, null=True, verbose_name="Code and name"
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="other2",
            field=models.CharField(
                blank=True, max_length=25, null=True, verbose_name="Code and name"
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="parent_nut_days",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="parent_nutn",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                max_length=2,
                verbose_name="parenteral nutrition",
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="pda_proph_indom",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                max_length=2,
                verbose_name="PDA prophil. indometacina",
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="sepsis_yes_no",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                max_length=2,
                verbose_name="SEPSIS",
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="sev_cog_def",
            field=models.CharField(
                blank=True,
                max_length=25,
                null=True,
                verbose_name="Severe congenital defect",
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="surf_cnt",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                max_length=2,
                verbose_name="Surfactant",
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="surf_cnt_age_first_dose",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="teoph_cafeine",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                max_length=2,
                verbose_name="teoph/cafeine",
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="teoph_cafeine_days",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name="specialcare",
            name="brain_max_grade",
            field=models.CharField(
                choices=[("1", "1"), ("2", "2"), ("3", "3"), ("4", "4")],
                default="1",
                max_length=1,
                verbose_name="max grade",
            ),
        ),
        migrations.AlterField(
            model_name="specialcare",
            name="rop_max_grade",
            field=models.CharField(
                choices=[
                    ("0", "0"),
                    ("1", "1"),
                    ("2", "2"),
                    ("3", "3"),
                    ("4", "4"),
                    ("5", "5"),
                ],
                default="0",
                max_length=1,
                verbose_name="max grade",
            ),
        ),
    ]
