# Generated by Django 4.2.2 on 2023-06-19 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_rename_sepsis4_agent_specialcare_sepsis_agent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialcare",
            name="blood_prods",
            field=models.CharField(
                blank=True,
                max_length=4,
                null=True,
                verbose_name="blood products Volume",
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="imv_ettube",
            field=models.CharField(
                blank=True,
                max_length=5,
                null=True,
                verbose_name="IMV-ETTube days/hours",
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="ncpap",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                max_length=2,
                verbose_name="nCPAP",
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="ncpap_days",
            field=models.CharField(
                blank=True, max_length=4, null=True, verbose_name="nCPAP days"
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="ox_over_28_days",
            field=models.BooleanField(default=False, verbose_name="over 28 days"),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="pre_vent_ncpap",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                max_length=2,
                verbose_name="pre_VENT nCPAP",
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="res_supp_oxygen",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                max_length=2,
                verbose_name="oxygen",
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="res_supp_oxygen_days",
            field=models.CharField(
                blank=True, max_length=4, null=True, verbose_name="oxygen days"
            ),
        ),
        migrations.AlterField(
            model_name="specialcare",
            name="fio2",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Fraction of inspired res_supp_"
            ),
        ),
        migrations.AlterField(
            model_name="specialcare",
            name="oxygen",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")], default="N", max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="specialcare",
            name="parent_nut_days",
            field=models.CharField(
                blank=True,
                max_length=4,
                null=True,
                verbose_name="parenteral nutrition day",
            ),
        ),
        migrations.AlterField(
            model_name="specialcare",
            name="sa02",
            field=models.CharField(
                max_length=255, null=True, verbose_name="res_supp_ saturation"
            ),
        ),
        migrations.AlterField(
            model_name="specialcare",
            name="surf_cnt_age_first_dose",
            field=models.CharField(
                blank=True, max_length=4, null=True, verbose_name="age first dose"
            ),
        ),
        migrations.AlterField(
            model_name="specialcare",
            name="teoph_cafeine_days",
            field=models.CharField(
                blank=True, max_length=4, null=True, verbose_name="teoph/cafeine days"
            ),
        ),
    ]
