# Generated by Django 4.2.2 on 2023-06-19 22:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_specialcare_blood_prods_specialcare_imv_ettube_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialcare",
            name="blood_prods_vol",
            field=models.CharField(
                blank=True,
                max_length=4,
                null=True,
                verbose_name="blood products Volume",
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="imv_ettube_days_hrs",
            field=models.CharField(
                blank=True,
                help_text="DDD/HH",
                max_length=5,
                null=True,
                verbose_name="IMV-ETTube days/hours",
            ),
        ),
        migrations.AlterField(
            model_name="specialcare",
            name="blood_prods",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                max_length=2,
                verbose_name="blood products",
            ),
        ),
        migrations.AlterField(
            model_name="specialcare",
            name="imv_ettube",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                max_length=2,
                verbose_name="IMV-ETTube",
            ),
        ),
    ]
