# Generated by Django 4.2.2 on 2023-06-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_specialcare_blood_prods_vol_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialcare",
            name="age_at_bw_recv",
            field=models.CharField(
                blank=True, max_length=25, null=True, verbose_name="age at BW recovered"
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="anthy_dschag_head_cir",
            field=models.CharField(
                blank=True, max_length=25, null=True, verbose_name="weight (g)"
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="anthy_dschag_length",
            field=models.CharField(
                blank=True, max_length=25, null=True, verbose_name="length (cm)"
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="anthy_dschrg_weight",
            field=models.CharField(
                blank=True, max_length=25, null=True, verbose_name="weight (g)"
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="at_36_wks_ga",
            field=models.CharField(
                blank=True, max_length=25, null=True, verbose_name="at 36 weeks GA"
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="dschrg",
            field=models.CharField(
                choices=[("L", "Live"), ("D", "Dead"), ("T", "Transfer")],
                default="L",
                max_length=2,
                verbose_name="other",
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="dschrg_age",
            field=models.CharField(
                blank=True, max_length=5, null=True, verbose_name="age"
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="dschrg_age_less_one_day",
            field=models.BooleanField(default=False, verbose_name="< 1 day"),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="dschrg_at_home",
            field=models.CharField(
                choices=[
                    ("DN", "day and night"),
                    ("D", "Only day"),
                    ("V", "Only Visit"),
                    ("N", "None"),
                ],
                default="WP",
                max_length=2,
                verbose_name="home at discharge",
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="dschrg_feeding",
            field=models.CharField(
                choices=[("B", "Breast"), ("P", "Partial"), ("F", "Formula")],
                default="B",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="dschrg_gest_age_correct",
            field=models.CharField(
                blank=True, max_length=5, null=True, verbose_name="GEST AGE CORRECTED"
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="dschrg_ind_prscrb_by",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="prescribed by"
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="dschrg_ind_prscrb_details",
            field=models.TextField(blank=True, null=True, verbose_name="details"),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="dschrg_ind_prscrb_email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="email"
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="dschrg_ind_prscrb_phn",
            field=models.CharField(max_length=50, null=True, verbose_name="phone"),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="dschrg_post_mort",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                max_length=2,
                verbose_name="post mortem",
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="dschrg_room_in",
            field=models.CharField(
                choices=[
                    ("DN", "day and night"),
                    ("D", "Only day"),
                    ("V", "Only Visit"),
                    ("N", "None"),
                ],
                default="N",
                max_length=2,
                verbose_name="rooming-in previous day",
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="dschrg_trans_dies",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                max_length=2,
                verbose_name="Dies during transfer or at transfer place",
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="dschrg_trans_plc",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="place"
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="dschrg_value",
            field=models.CharField(
                blank=True, max_length=25, null=True, verbose_name="dia/mes/ano"
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="follow_up_eye_dt",
            field=models.DateField(blank=True, null=True, verbose_name="date"),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="follow_up_eye_phn",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="phone"
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="follow_up_eye_plc",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="place"
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="follow_up_hear_dt",
            field=models.DateField(blank=True, null=True, verbose_name="date"),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="follow_up_hear_phn",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="phone"
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="follow_up_hear_plc",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="place"
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="follow_up_mthr_sty_hm",
            field=models.CharField(
                blank=True,
                max_length=2,
                null=True,
                verbose_name="how long the mother will be free to stay at home all day",
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="follow_up_mthr_sty_hm_fr_wks",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="follow_up_ped_dt",
            field=models.DateField(blank=True, null=True, verbose_name="date"),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="follow_up_ped_phn",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="phone"
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="follow_up_ped_plc",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="place"
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="follow_up_psych_dt",
            field=models.DateField(blank=True, null=True, verbose_name="date"),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="follow_up_psych_phn",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="phone"
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="follow_up_psych_plc",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="place"
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="h_prom_bck_slp",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="Y",
                max_length=2,
                verbose_name="Back to sleep",
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="h_prom_brst_feed",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="Y",
                max_length=2,
                verbose_name="Exclusive breast feeding",
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="h_prom_edu_mat",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="Y",
                max_length=2,
                verbose_name="educational material",
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="h_prom_hand_hygn",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="Y",
                max_length=2,
                verbose_name="Hand hygiene/alcohol rub",
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="h_prom_resp_prev",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="Y",
                max_length=2,
                verbose_name="respivirius prevention",
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="h_prom_scl_prot",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="Y",
                max_length=2,
                verbose_name="Social Protection/family rights",
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="health_prom_details",
            field=models.TextField(
                blank=True, null=True, verbose_name="Health Promotion"
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="lowest_weight",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="scrn_tst_bcg",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "NO"), ("UK", "Unknown")],
                default="N",
                max_length=2,
                verbose_name="BCG",
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="scrn_tst_hear",
            field=models.CharField(
                choices=[("N", "Normal"), ("D", "Deficit"), ("UK", "Unknown")],
                default="N",
                max_length=2,
                verbose_name="Hearing",
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="scrn_tst_hep_b",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "NO"), ("UK", "Unknown")],
                default="N",
                max_length=2,
                verbose_name="Hep B",
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="scrn_tst_sickle",
            field=models.CharField(
                choices=[("N", "Normal"), ("AN", "Abnormal"), ("UK", "Unknown")],
                default="N",
                max_length=2,
                verbose_name="sickle cell",
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="scrn_tst_syph",
            field=models.CharField(
                choices=[
                    ("N", "Negative"),
                    ("PT", "+ Treated"),
                    ("PU", "+ Untreated"),
                    ("UK", "Unknown"),
                ],
                default="N",
                max_length=2,
                verbose_name="syphilis",
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="scrn_tst_tsh",
            field=models.CharField(
                choices=[("N", "Normal"), ("H", "High"), ("UK", "Unknown")],
                default="N",
                max_length=2,
                verbose_name="TSH",
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="surg_nec",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                max_length=2,
                verbose_name="NEC",
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="surg_other",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                max_length=2,
                verbose_name="other",
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="surg_other_value",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="other"
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="surg_pda",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                max_length=2,
                verbose_name="PDA",
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="surg_rop",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                max_length=2,
                verbose_name="ROP",
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="surg_vp_sht",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                max_length=2,
                verbose_name="VP Shunt",
            ),
        ),
        migrations.AlterField(
            model_name="specialcare",
            name="blood_prods_vol",
            field=models.CharField(
                blank=True,
                help_text="ml Vol. total",
                max_length=4,
                null=True,
                verbose_name="blood products Volume",
            ),
        ),
        migrations.AlterField(
            model_name="specialcare",
            name="ox_over_28_days",
            field=models.BooleanField(default=False, verbose_name="> 28 days"),
        ),
        migrations.AlterField(
            model_name="specialcare",
            name="pre_vent_ncpap",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                max_length=2,
                verbose_name="pre-VENT nCPAP",
            ),
        ),
    ]
