# Generated by Django 4.2.2 on 2023-06-24 12:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_specialcare_age_at_bw_recv_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="specialcare",
            old_name="surg_other_value",
            new_name="surg_other_details",
        ),
    ]
