# Generated by Django 4.2.2 on 2023-06-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_rename_dschrg_value_specialcare_dschrg_details_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialcare",
            name="follow_up_ped",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                max_length=2,
                verbose_name="Pediatric",
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="follow_up_psych",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                max_length=2,
                verbose_name="psychosocial support",
            ),
        ),
        migrations.AlterField(
            model_name="specialcare",
            name="dschrg_age",
            field=models.CharField(
                blank=True, help_text="DD", max_length=5, null=True, verbose_name="age"
            ),
        ),
        migrations.AlterField(
            model_name="specialcare",
            name="dschrg_at_home",
            field=models.CharField(
                choices=[
                    ("WP", "With parents"),
                    ("WR", "With relatives"),
                    ("AP", "Adopted parents"),
                    ("FC", "Foster care"),
                    ("N/A", "N/A"),
                ],
                default="WP",
                max_length=3,
                verbose_name="home at discharge",
            ),
        ),
        migrations.AlterField(
            model_name="specialcare",
            name="dschrg_gest_age_correct",
            field=models.CharField(
                blank=True,
                help_text="WW/D",
                max_length=5,
                null=True,
                verbose_name="GEST AGE CORRECTED",
            ),
        ),
        migrations.AlterField(
            model_name="specialcare",
            name="dschrg_post_mort",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                max_length=2,
                verbose_name="post mortem",
            ),
        ),
        migrations.AlterField(
            model_name="specialcare",
            name="dschrg_room_in",
            field=models.CharField(
                choices=[
                    ("DN", "Day and night"),
                    ("D", "Only day"),
                    ("V", "Only Visit"),
                    ("N", "None"),
                ],
                default="N",
                max_length=2,
                verbose_name="rooming-in previous day",
            ),
        ),
        migrations.AlterField(
            model_name="specialcare",
            name="scrn_tst_bcg",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No"), ("UK", "Unknown")],
                default="N",
                max_length=2,
                verbose_name="BCG",
            ),
        ),
    ]
