# Generated by Django 4.2.2 on 2023-06-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_specialcare_follow_up_ped_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialcare",
            name="follow_up_eye",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                max_length=2,
                verbose_name="eye doctor",
            ),
        ),
        migrations.AddField(
            model_name="specialcare",
            name="follow_up_hear",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                max_length=2,
                verbose_name="hearing test",
            ),
        ),
        migrations.AlterField(
            model_name="specialcare",
            name="dschrg_ind_prscrb_details",
            field=models.TextField(blank=True, null=True),
        ),
    ]
