# Generated by Django 4.2.2 on 2023-06-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_specialcare_follow_up_eye_specialcare_follow_up_hear_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specialcare",
            name="iv_vol",
            field=models.CharField(
                blank=True,
                default=0,
                max_length=3,
                null=True,
                verbose_name="I/V Volume",
            ),
        ),
        migrations.AlterField(
            model_name="specialcare",
            name="scrn_tst_hep_b",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No"), ("UK", "Unknown")],
                default="N",
                max_length=2,
                verbose_name="Hep B",
            ),
        ),
        migrations.AlterField(
            model_name="specialcare",
            name="trans_dura",
            field=models.CharField(
                blank=True,
                default=0,
                help_text="HH/MM | (02/45) | 2 hrs 45 mins",
                max_length=4,
                null=True,
                verbose_name="duration",
            ),
        ),
        migrations.AlterField(
            model_name="specialcare",
            name="trans_km",
            field=models.CharField(
                blank=True,
                default=0,
                help_text="KM",
                max_length=4,
                null=True,
                verbose_name="distance",
            ),
        ),
    ]
