from django import forms

from .models import SpecialCare


class SpecialCareForm(forms.ModelForm):
    class Meta:
        model = SpecialCare
        fields = "__all__"
        labels = {
            "pob": "",
            "name": "",
            "neo_record_no": "",
            "mother_name": "",
            "mat_record_no": "",
            "trans_reason": "",
            "drugs": "",
            "father_name": "",
            "father_addr": "",
            "father_email": "",
            "father_phone": "",
            "admin_to": "",
            "nurse": "",
            "doctor": "",
            "ax_temp": "",
            "sa02": "",
            "fio2": "",
            "weight": "",
            "length": "",
            "head_c": "",
            "first_exam_corrected_ga": "",
        }
        widgets = {
            "sip": forms.RadioSelect(),
            "pob": forms.TextInput(attrs={"placeholder": "Place of Birth"}),
            "name": forms.TextInput(attrs={"placeholder": "Name"}),
            "id_band": forms.RadioSelect(),
            "neo_record_no": forms.TextInput(
                attrs={"placeholder": "Neonatal Record Number"}
            ),
            "mother_name": forms.TextInput(attrs={"placeholder": "Mother's name"}),
            "stays_at": forms.RadioSelect(),
            "health_status": forms.RadioSelect(),
            "idd_new_born": forms.RadioSelect(),
            "father_name": forms.TextInput(attrs={"placeholder": "Father's name"}),
            "father_addr": forms.TextInput(attrs={"placeholder": "Father's address"}),
            "father_email": forms.TextInput(attrs={"placeholder": "Father's email"}),
            "father_phone": forms.Textarea(
                attrs={"rows": "3", "placeholder": "Phones"}
            ),
            "trans_from": forms.RadioSelect(),
            "transport_type": forms.RadioSelect(),
            "trans_dura": forms.TextInput(attrs={"placeholder": "02/45"}),
            "incubator": forms.RadioSelect(),
            "iv": forms.RadioSelect(),
            "drugs": forms.Textarea(attrs={"rows": "3", "placeholder": ""}),
            "monitors": forms.RadioSelect(),
            "oxygen": forms.RadioSelect(),
            "cpap": forms.RadioSelect(),
            "ettube": forms.RadioSelect(),
            "is_drugged": forms.RadioSelect(),
            "trans_comp": forms.RadioSelect(),
            "mat_record_no": forms.TextInput(
                attrs={"placeholder": "Maternal Record Number"}
            ),
            "trans_reason": forms.TextInput(
                attrs={"placeholder": "Reason for admission"}
            ),
            "transport": forms.RadioSelect(),
            "admin_to": forms.TextInput(attrs={"placeholder": "Admitted to"}),
            "nurse": forms.TextInput(attrs={"placeholder": "Nurse"}),
            "doctor": forms.TextInput(attrs={"placeholder": "Doctor"}),
            "admin_date_time": forms.TextInput(attrs={"type": "datetime-local"}),
            "admin_age": forms.TextInput(attrs={"placeholder": "02/05"}),
            "ax_temp": forms.TextInput(attrs={"placeholder": "Axillary temperature"}),
            "sa02": forms.TextInput(attrs={"placeholder": "Oxygen saturation"}),
            "fio2": forms.TextInput(
                attrs={"placeholder": "Fraction of inspired oxygen"}
            ),
            "cyano": forms.RadioSelect(),
            "rds": forms.RadioSelect(),
            "pale": forms.RadioSelect(),
            "diur": forms.RadioSelect(),
            "alert": forms.RadioSelect(),
            "seizures": forms.RadioSelect(),
            "weight": forms.TextInput(attrs={"placeholder": "Weight (g)"}),
            "length": forms.TextInput(attrs={"placeholder": "Length (cm)"}),
            "head_c": forms.TextInput(attrs={"placeholder": "Head circumference (cm)"}),
            "first_report": forms.RadioSelect(),
            "dob": forms.TextInput(attrs={"type": "date"}),
            "tob": forms.TextInput(attrs={"type": "time"}),
            "gender": forms.RadioSelect(),
            "diseases": forms.RadioSelect(),
            "gender": forms.RadioSelect(),
            "birth_asp": forms.RadioSelect(),
            "hmd": forms.RadioSelect(),
            "rds_meconium": forms.RadioSelect(),
            "pphn": forms.RadioSelect(),
            "pda": forms.RadioSelect(),
            "apneas": forms.RadioSelect(),
            "pneum": forms.RadioSelect(),
            "bpd": forms.RadioSelect(),
            "nec": forms.RadioSelect(),
            "sbp": forms.RadioSelect(),
            "syp": forms.RadioSelect(),
            "per_hiv": forms.RadioSelect(),
            "sepsis1_yes_no": forms.RadioSelect(),
            "sepsis2_yes_no": forms.RadioSelect(),
            "sepsis3_yes_no": forms.RadioSelect(),
            "sepsis_yes_no": forms.RadioSelect(),
            "sepsis1_date_treated": forms.TextInput(attrs={"type": "date"}),
            "sepsis2_date_treated": forms.TextInput(attrs={"type": "date"}),
            "sepsis3_date_treated": forms.TextInput(attrs={"type": "date"}),
            "sepsis_date_treated": forms.TextInput(attrs={"type": "date"}),
            "ind_opht": forms.RadioSelect(),
            "rop_max_grade": forms.RadioSelect(),
            "surg_ind": forms.RadioSelect(),
            "first_exam_corrected_ga": forms.TextInput(
                attrs={"placeholder": "1st exam corrected GA"}
            ),
            "us_scan": forms.RadioSelect(),
            "leukom": forms.RadioSelect(),
            "intra_hemo": forms.RadioSelect(),
            "brain_max_grade": forms.RadioSelect(),
            "birth_asph_seiz": forms.RadioSelect(),
            "surf_cnt": forms.RadioSelect(),
            "pda_proph_indom": forms.RadioSelect(),
            "indo_treat": forms.RadioSelect(),
            "teoph_cafeine": forms.RadioSelect(),
            "parent_nutn": forms.RadioSelect(),
            "pre_vent_ncpap": forms.RadioSelect(),
            "imv_ettube": forms.RadioSelect(),
            "ncpap": forms.RadioSelect(),
            "res_supp_oxygen": forms.RadioSelect(),
            "blood_prods": forms.RadioSelect(),
        }
